[tox]
envlist =
  py{3.6,3.7,3.8,3.9,3.10,3.11,3.12,3.13,3.14}-cryptography{40.0.2}
  postgres
  windows

[testenv]
allowlist_externals=
  sh

deps =
  cryptography40.0.2: cryptography==40.0.2

extras =
  test

setenv =
  PYTHONPATH = {toxinidir}{:}{toxinidir}/tests/testapp

commands =
  sh -c 'tests/testapp/manage.py makemigrations --check'
  python -O -m pytest {posargs: --color=no}

[testenv:postgres]
extras =
  test
  postgres

setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/tests/testapp
  DJANGO_SETTINGS_MODULE = testapp.postgres_settings

commands =
  python -O -m pytest {posargs: --color=no}

[testenv:windows]
extras =
  test

setenv =
  PYTHONPATH = {toxinidir}{:}{toxinidir}/tests/testapp

commands =
  python -O -m pytest {posargs: --color=no} -m windows
