# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
