# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-27 04:49
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
