# Generated by Django 3.2.23 on 2024-01-29 20:25
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_profile', '0002_auto_20220427_0449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyParent',
        ),
        migrations.DeleteModel(
            name='ProxyModel',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='level',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='facility_profile.facility'
            ),
        ),
    ]
