# Generated by Django 3.2.25 on 2025-09-22 23:23
from django.db import migrations
from django.db import models

import morango.models.fields.uuids


class Migration(migrations.Migration):
    dependencies = [
        ("facility_profile", "0003_auto_20240129_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    morango.models.fields.uuids.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("_morango_dirty_bit", models.BooleanField(default=True, editable=False)),
                ("_morango_source_id", models.CharField(editable=False, max_length=96)),
                ("_morango_partition", models.CharField(editable=False, max_length=128)),
                ("name", models.CharField(max_length=100)),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
