# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import morango.utils.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedModels',
            fields=[
                ('id', morango.utils.uuids.UUIDField(primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_timestamp', models.DateTimeField(blank=True)),
                ('scope_setting', models.TextField(default=b'{}')),
                ('current_transfer', models.UUIDField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('filters', models.TextField(default=b'{}')),
                ('records_left', models.IntegerField()),
                ('push_request', models.BooleanField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='certificate',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
