# Generated by Django 3.2.24 on 2024-10-18 23:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("morango", "0001_squashed_0024_auto_20240129_1757"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                condition=models.Q(("dirty_bit", True)),
                fields=["profile", "model_name", "partition", "dirty_bit"],
                name="idx_morango_deserialize",
            ),
        ),
    ]
