# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-13 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buffer',
            name='_self_ref_fk',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='store',
            name='_self_ref_fk',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
