# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfersession',
            name='local_fsic',
            field=models.TextField(blank=True, default=b'{}'),
        ),
        migrations.AddField(
            model_name='transfersession',
            name='remote_fsic',
            field=models.TextField(blank=True, default=b'{}'),
        ),
    ]
