# Generated by Django 3.2.25 on 2026-04-14 15:54
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("morango", "0002_store_idx_morango_deserialize"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="deserialization_exception",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="deserialization_error",
            field=models.TextField(blank=True, null=True),
        ),
    ]
