# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 05:43
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("morango", "0002_auto_20170511_0400")]

    operations = [
        migrations.AlterModelManagers(name="certificate", managers=[]),
        migrations.RenameField(
            model_name="scopedefinition", old_name="scope_id", new_name="id"
        ),
        migrations.AddField(
            model_name="scopedefinition",
            name="primary_scope_param_key",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
