# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("morango", "0003_auto_20170519_0543")]

    operations = [
        migrations.RemoveField(model_name="scopedefinition", name="key"),
        migrations.RemoveField(model_name="scopedefinition", name="serialized"),
        migrations.RemoveField(model_name="scopedefinition", name="signature"),
        migrations.DeleteModel(name="TrustedKey"),
    ]
