# Generated by Django 3.2.25 on 2026-04-22 10:53

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("morango", "0004_deferrable_foreign_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="buffer",
            name="_self_ref_order",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="_self_ref_order",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
