# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-18 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0006_instanceidmodel_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='dirty_bit',
            field=models.BooleanField(default=False),
        ),
    ]
