# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0007_store_dirty_bit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopedefinition',
            old_name='read_scope_def',
            new_name='read_filter_template',
        ),
        migrations.RenameField(
            model_name='scopedefinition',
            old_name='read_write_scope_def',
            new_name='read_write_filter_template',
        ),
        migrations.RenameField(
            model_name='scopedefinition',
            old_name='write_scope_def',
            new_name='write_filter_template',
        ),
    ]
