# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-14 22:17
from __future__ import unicode_literals

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("morango", "0007_auto_20171018_1615")]

    operations = [
        migrations.RenameField(
            model_name="syncsession",
            old_name="local_instance",
            new_name="client_instance",
        ),
        migrations.RenameField(
            model_name="syncsession", old_name="local_ip", new_name="client_ip"
        ),
        migrations.RenameField(
            model_name="syncsession",
            old_name="remote_instance",
            new_name="server_instance",
        ),
        migrations.RenameField(
            model_name="syncsession", old_name="remote_ip", new_name="server_ip"
        ),
        migrations.RenameField(
            model_name="transfersession", old_name="local_fsic", new_name="client_fsic"
        ),
        migrations.RenameField(
            model_name="transfersession", old_name="remote_fsic", new_name="server_fsic"
        ),
        migrations.RemoveField(model_name="syncsession", name="local_certificate"),
        migrations.RemoveField(model_name="syncsession", name="remote_certificate"),
        migrations.AddField(
            model_name="syncsession",
            name="client_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syncsessions_client",
                to="morango.Certificate",
            ),
        ),
        migrations.AddField(
            model_name="syncsession",
            name="server_certificate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syncsessions_server",
                to="morango.Certificate",
            ),
        ),
    ]
