# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0008_auto_20170731_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncsession',
            name='host',
        ),
        migrations.RemoveField(
            model_name='syncsession',
            name='local_scope',
        ),
        migrations.RemoveField(
            model_name='syncsession',
            name='remote_scope',
        ),
        migrations.AddField(
            model_name='syncsession',
            name='local_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncsessions_local', to='morango.Certificate'),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='remote_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syncsessions_remote', to='morango.Certificate'),
        ),
        migrations.CreateModel(
            name='DiskSyncSession',
            fields=[
                ('syncsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='morango.SyncSession')),
                ('path', models.CharField(max_length=1000)),
            ],
            bases=('morango.syncsession',),
        ),
        migrations.CreateModel(
            name='NetworkSyncSession',
            fields=[
                ('syncsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='morango.SyncSession')),
                ('host', models.CharField(max_length=1000)),
            ],
            bases=('morango.syncsession',),
        ),
    ]
