# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-02 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0009_auto_20170731_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasemaxcounter',
            name='filter',
        ),
        migrations.AddField(
            model_name='databasemaxcounter',
            name='partition',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
