# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-12-06 22:15
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("morango", "0009_auto_20171205_0252")]

    operations = [
        migrations.AlterField(
            model_name="databasemaxcounter",
            name="partition",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="transfersession",
            name="client_fsic",
            field=models.TextField(blank=True, default="{}"),
        ),
        migrations.AlterField(
            model_name="transfersession",
            name="server_fsic",
            field=models.TextField(blank=True, default="{}"),
        ),
    ]
