# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0009_auto_20170731_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncsession',
            name='connection_params',
        ),
        migrations.AddField(
            model_name='syncsession',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='local_instance',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='local_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='remote_instance',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='remote_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transfersession',
            name='last_activity_timestamp',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfersession',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
