# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-07 16:14
from __future__ import unicode_literals

from django.db import migrations
import morango.utils.uuids


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0010_auto_20170807_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffer',
            name='id',
            field=morango.utils.uuids.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
