# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0010_auto_20171206_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfersession',
            name='transfer_stage',
            field=models.CharField(blank=True, choices=[('started', 'Started'), ('queuing', 'Queuing'), ('dequeuing', 'Dequeuing'), ('pushing', 'Pushing'), ('pulling', 'Pulling'), ('completed', 'Completed')], max_length=20),
        ),
    ]
