# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-03 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0010_auto_20170803_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='salt',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
