# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0011_auto_20170807_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsession',
            name='profile',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
