# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 22:13
from __future__ import unicode_literals

from django.db import migrations

import morango.models.fields.uuids


class Migration(migrations.Migration):

    dependencies = [("morango", "0012_auto_20180927_1658")]

    operations = [
        migrations.AlterField(
            model_name="recordmaxcounterbuffer",
            name="model_uuid",
            field=morango.models.fields.uuids.UUIDField(db_index=True),
        )
    ]
