# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-05 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0013_auto_20170805_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsession',
            name='is_server',
            field=models.BooleanField(default=False),
        ),
    ]
