# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-13 18:22
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("morango", "0013_auto_20190627_1513")]

    operations = [
        migrations.AddField(
            model_name="transfersession",
            name="transfer_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "Started"),
                    ("queuing", "Queuing"),
                    ("dequeuing", "Dequeuing"),
                    ("pushing", "Pushing"),
                    ("pulling", "Pulling"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                max_length=20,
            ),
        )
    ]
