# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("morango", "0014_syncsession_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfersession",
            name="bytes_received",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="transfersession",
            name="bytes_sent",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
