# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 02:51
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0014_syncsession_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncsession',
            name='client_metadata',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='syncsession',
            name='server_metadata',
            field=models.TextField(default='{}'),
        ),
    ]
