# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 21:03
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("morango", "0014_transfersession_transfer_stage")]

    operations = [
        migrations.AddField(
            model_name="syncsession",
            name="client_pid",
            field=models.CharField(blank=True, max_length=10),
        )
    ]
