# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-12 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("morango", "0016_store_deserialization_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfersession",
            name="transfer_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("initializing", "Initializing"),
                    ("serializing", "Serializing"),
                    ("queuing", "Queuing"),
                    ("transferring", "Transferring"),
                    ("dequeuing", "Dequeuing"),
                    ("deserializing", "Deserializing"),
                    ("cleanup", "Cleanup"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transfersession",
            name="transfer_stage_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("completed", "Completed"),
                    ("errored", "Errored"),
                ],
                max_length=20,
            ),
        ),
    ]
