# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("morango", "0017_auto_20210512_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="syncsession",
            name="process_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
