# Generated by Django 3.2.23 on 2024-01-29 17:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('morango', '0023_add_instance_id_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
