name: Docs

on:
  push:
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    name: Checking docs build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
      - name: Install system dependencies
        run: |
          sudo apt-get -y -qq update
          sudo apt-get install -y swig openssl libssl-dev
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.10"
          activate-environment: "true"
          enable-cache: "true"
      - name: Install dependencies
        run: uv sync --frozen --group docs
      - name: Check Docs build
        run: make docs
