name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: 3.9
          activate-environment: "true"
          enable-cache: "true"
      - name: Build package
        run: uv build
      - name: Publish package
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
