name: Python 2 linting

on: [push, pull_request]

jobs:
    pre_job:
        name: Path match check
        runs-on: ubuntu-latest
        # Map a step output to a job output
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip }}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@master
              with:
                  github_token: ${{ github.token }}
                  paths: '["morango/**.py"]'
    lint:
        name: Python 2 syntax checking
        needs: pre_job
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        runs-on: ubuntu-20.04
        container:
            image: python:2.7.18-buster
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8
            - name: Lint with flake8
              run: |
                  flake8 morango
